image: romansey/example-service:latest
response: "Chart Default Response"
service:
  name:
  type: ClusterIP
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "500m"