apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: exampleservices.example.org
spec:
  group: example.org
  names:
    kind: ExampleService
    listKind: ExampleServiceList
    plural: exampleservices
    singular: exampleservice
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
